-- Default configuration for Talkies
Talkies.textSpeed = "fast"
Talkies.talkSound = love.audio.newSource("sfx/typeSound.wav", "static")
Talkies.optionSwitchSound = love.audio.newSource("sfx/optionSwitch.wav", "static")
Talkies.indicatorCharacter = ">"
Talkies.optionCharacter = "> "
Talkies.inlineOptions = true
Talkies.font = love.graphics.newFont("fonts/Pixel UniCode.ttf", 32)
Talkies.padding = 32
Talkies.thickness = 1
Talkies.rounding = 10
Talkies.titleColor = {1, 1, 1}
Talkies.titleBackgroundColor = nil
Talkies.titleBorderColor = nil
Talkies.messageColor = {1, 1, 1}
Talkies.messageBackgroundColor = {0, 0, 0, 0.8}
Talkies.messageBorderColor = nil
Talkies.typedNotTalked = false
Talkies.pitchValues = {0.7, 0.8, 1.0, 1.2, 1.3}
Talkies.height = 128